[supabase]
SUPABASE_URL = "https://sbdedhvzitxgvxsnkxqc.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNiZGVkaHZ6aXR4Z3Z4c25reHFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2NTg0NTEsImV4cCI6MjA1NzIzNDQ1MX0.NiASD4LrhnZEcywurrNxhc4zD5GoKLbLNEUWiimIgpY"
